name: Checkout Workflow
on: push
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - run: ls -al
            - uses: actions/checkout@v3
            - run: ls -al
            - run: cat .github/workflows/checkout.yml
            - name: set a path
              uses: actions/checkout@v3
              with:
                  path: our-source
            - run: ls -al
            - run: ls -al our-source
            - name: checkout github actions/checkout
              uses: actions/checkout@v3
              with:
                  repository: actions/checkout
                  ref: v3
            - run: ls -al
